### PR TITLE
add sane-term-prev command and make sane-term-next interactive

### PR DESCRIPTION
**Pull request by jpkotta**

### CODE REVIEW

**Comment by adamrt** [comment]
Thanks, overall I like this. Also sorry I was out of town until just now. I only ever have a few terminals so I just cycle through but I can see this being useful for other workflows

Is there a reason you named the new function `sane-term--next-1`? My elisp isn't top-notch so I may not know about the "-1" and double hyphen usage.

Maybe `sane-term-cycle` makes more sense if those are not some precedent. Thoughts?

**Comment by jpkotta** [comment]
The double dash is to denote "private" functions and variables, like leading underscore(s) in Python.  The "-1" (or "-2", etc.) is sometimes used for helper functions.  You can see examples of these conventions in Emacs (an example is `custom--sort-vars-1`).  That said, I'm not sure how strongly recommended (or discouraged) these conventions are.  It doesn't really matter to me if you rename things.

**Comment by jpkotta** [comment]
Ping

**Comment by adamrt** [comment]
@jpkotta Hey thank you for your pull request. Real life got in the way so I appreciate the follow up. I've merged this and then renamed the function to `sane-term-cycle`.

Thanks again and sorry for the delay. Future contributions will be handled more swiftly!

**Pull request merged**
